### ISSUE TITLE
M1 Mac support?

### ISSUE THREAD

**Issue by magnusviri** [wol101/GaitSym2019#1]
I am having trouble with GaitSym2019 on M1 Macs. It's very slow and this is what it looks like.
<img width="1269" alt="Screen Shot 2021-05-13 at 3 08 36 PM" src="https://user-images.githubusercontent.com/711269/118188985-6f947f00-b3fe-11eb-888b-8bed3c4b5f6f.png">

**Comment by wol101** [comment]
I've done some very limited testing on the new Mac M1 chip. As far as I can see, the Mac Intel binary seems to still work under Rosetta on the M1. I've also tried compiling using native Qt and everything works except the OpenGL 3D rendering. I'm guessing that's what your screen shot shows. I need to get some help from someone who know more about OpenGL on the Mac M1 because it all works on Linux, Windows, Intel Mac and Raspberry Pi (and my OpenGL is really simple) and I am a bit stumped about what to try. My guess would be the shaders but they are pretty straightforward.

**Comment by wol101** [comment]
OK, this was due to a Qt bug in QSurfaceFormat. I've implemented a workaround that should be fine going forward. The latest source updates fix this bug on my MacBookAir M1 so please try compiling it. I will produce a new release soon with versions for M1. I don't think Qt can produce fat binaries yet so it will be a separate release.
